In [1]:
import torch


### 各次元における最大値
a = torch.tensor([[[2,3,4],[2,3,3]],[[1,4,6],[23,52,2]]])
## argmax
print(a.argmax(0))
print([0,0])
print(a.argmax(1))
print([[0,0,0],[1,1,0]])
print(a.argmax(2))
print([[2,1],[2,1]])
print()

### torch.max
print(torch.max(a,1))



###　単位行列を作成
print("torch.eye")
inp = torch.eye(5,requires_grad=True)
print(inp)


### tensorの全要素のn乗を計算
out = (inp+1).pow(2)
print(out)


tensor([[0, 1, 1],
        [1, 1, 0]])
[0, 0]
tensor([[0, 0, 0],
        [1, 1, 0]])
[[0, 0, 0], [1, 1, 0]]
tensor([[2, 1],
        [2, 1]])
[[2, 1], [2, 1]]

torch.return_types.max(
values=tensor([[ 2,  3,  4],
        [23, 52,  6]]),
indices=tensor([[0, 0, 0],
        [1, 1, 0]]))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)
tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)


In [5]:
b = torch.arange(9).reshape(3,3)
print(b)
## topk(n)nはどこまでの最大値indexを取るか
print(b.topk(2))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.return_types.topk(
values=tensor([[2, 1],
        [5, 4],
        [8, 7]]),
indices=tensor([[2, 1],
        [2, 1],
        [2, 1]]))
